Evaluate page
ExpoAnyGate/E.A.G-classic pull request #33
Opened 2024-10-17 06:41 UTC by ucicu-hung

updated commit evaluate.scss&手機版nav show 問題

2024-10-22 16:58 UTC, J-I-P approved these changes

2024-10-22 17:07 UTC, J-I-P requested changes

2024-10-22 17:07 UTC, J-I-P commented on assets/scss/pages/_evaluate.scss
>  	display: none;
你這邊改掉了 
這樣小視窗的 navbar 會沒有運作喔~~!!!!!

2024-10-23 07:16 UTC, ucicu-hung commented on assets/scss/pages/_evaluate.scss
>  	display: none;
右邊的navbar 會在414以上會出現唷。
我css 改成這樣
@include media-breakpoint-up(md){
	.desktop{
		display: block;
	}
}

2024-10-23 12:38 UTC, J-I-P commented on assets/scss/pages/_evaluate.scss
>  	display: none;
<img width="758" alt="image" src="https://github.com/user-attachments/assets/60585ee4-8aa9-4dd7-852e-f6d416c74a8e">
所以不是為了隱藏這個右上的嗎？

2024-10-24 01:54 UTC, ucicu-hung commented on assets/scss/pages/_evaluate.scss
>  	display: none;
天啊，我css沒有更新上去。

2024-11-08 06:20 UTC, closed without merging